// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    DetectionControls: typeof import('./components/internals/DetectionControls.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FaceDetection: typeof import('./components/internals/FaceDetection.vue')['default']
    'ICarbon:maximize': typeof import('~icons/carbon/maximize')['default']
    'ICarbon:minimize': typeof import('~icons/carbon/minimize')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    IconButton: typeof import('./components/global/IconButton.vue')['default']
    'IMdi:flipHorizontal': typeof import('~icons/mdi/flip-horizontal')['default']
    'IMdi:video': typeof import('~icons/mdi/video')['default']
    'IMdi:videoOff': typeof import('~icons/mdi/video-off')['default']
    IRiBookmarkLine: typeof import('~icons/ri/bookmark-line')['default']
    IRiBugLine: typeof import('~icons/ri/bug-line')['default']
    IRiEyeClose: typeof import('~icons/ri/eye-close')['default']
    IRiEyeCloseLine: typeof import('~icons/ri/eye-close-line')['default']
    IRiEyeLine: typeof import('~icons/ri/eye-line')['default']
    IRiListOrdered: typeof import('~icons/ri/list-ordered')['default']
    IRiPauseLine: typeof import('~icons/ri/pause-line')['default']
    IRiPlayLine: typeof import('~icons/ri/play-line')['default']
    NavControls: typeof import('./components/internals/NavControls.vue')['default']
    VerticalDivider: typeof import('./components/internals/VerticalDivider.vue')['default']
    VtuberCanvas: typeof import('./components/internals/VtuberCanvas.vue')['default']
    VtuberConfig: typeof import('./components/vtuber/VtuberConfig.vue')['default']
    WebCamera: typeof import('./components/internals/WebCamera.vue')['default']
  }
}

export { }
