// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FaceDetection: typeof import('./components/FaceDetection.vue')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    VtuberCanvas: typeof import('./components/VtuberCanvas.vue')['default']
    VtuberConfig: typeof import('./components/vtuber/VtuberConfig.vue')['default']
  }
}

export { }
