// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    ElButton: typeof import('~icons/el/button')['default']
    ElContainer: typeof import('~icons/el/container')['default']
    ElHeader: typeof import('~icons/el/header')['default']
    ElMain: typeof import('~icons/el/main')['default']
    ElMenu: typeof import('~icons/el/menu')['default']
    ElMenuItem: typeof import('~icons/el/menu-item')['default']
    ElTooltip: typeof import('~icons/el/tooltip')['default']
    FaceDetection: typeof import('./components/FaceDetection.vue')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    VtuberCanvas: typeof import('./components/VtuberCanvas.vue')['default']
    VtuberConfig: typeof import('./components/vtuber/VtuberConfig.vue')['default']
  }
}

export { }
