// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutInfo: typeof import('./components/internals/AboutInfo.vue')['default']
    BaseFooter: typeof import('./components/layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    DetectionControls: typeof import('./components/internals/DetectionControls.vue')['default']
    FaceCanvas: typeof import('./components/internals/FaceCanvas.vue')['default']
    'ICarbon:maximize': typeof import('~icons/carbon/maximize')['default']
    'ICarbon:minimize': typeof import('~icons/carbon/minimize')['default']
    IconButton: typeof import('./components/global/IconButton.vue')['default']
    'IMdi:flipHorizontal': typeof import('~icons/mdi/flip-horizontal')['default']
    'IMdi:video': typeof import('~icons/mdi/video')['default']
    'IMdi:videoOff': typeof import('~icons/mdi/video-off')['default']
    IRiAccountCircleLine: typeof import('~icons/ri/account-circle-line')['default']
    IRiBodyScanLine: typeof import('~icons/ri/body-scan-line')['default']
    IRiBookLine: typeof import('~icons/ri/book-line')['default']
    IRiCameraLine: typeof import('~icons/ri/camera-line')['default']
    IRiEyeCloseLine: typeof import('~icons/ri/eye-close-line')['default']
    IRiEyeLine: typeof import('~icons/ri/eye-line')['default']
    IRiFileInfoLine: typeof import('~icons/ri/file-info-line')['default']
    IRiFileUserLine: typeof import('~icons/ri/file-user-line')['default']
    IRiGhostLine: typeof import('~icons/ri/ghost-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiMarkPenLine: typeof import('~icons/ri/mark-pen-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiPictureInPictureExitLine: typeof import('~icons/ri/picture-in-picture-exit-line')['default']
    IRiPictureInPictureLine: typeof import('~icons/ri/picture-in-picture-line')['default']
    IRiPlayLine: typeof import('~icons/ri/play-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTranslate: typeof import('~icons/ri/translate')['default']
    IRiUploadLine: typeof import('~icons/ri/upload-line')['default']
    IRiUserSearchLine: typeof import('~icons/ri/user-search-line')['default']
    IRiZoomInLine: typeof import('~icons/ri/zoom-in-line')['default']
    IRiZoomOutLine: typeof import('~icons/ri/zoom-out-line')['default']
    NavControls: typeof import('./components/internals/NavControls.vue')['default']
    OpenAnimation: typeof import('./components/internals/OpenAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusPanel: typeof import('./components/internals/StatusPanel.vue')['default']
    ToggleLocale: typeof import('./components/internals/control/ToggleLocale.vue')['default']
    ToggleVrm: typeof import('./components/vtuber/ToggleVrm.vue')['default']
    UploadButton: typeof import('./components/internals/control/UploadButton.vue')['default']
    VerticalDivider: typeof import('./components/internals/VerticalDivider.vue')['default']
    VtuberCanvas: typeof import('./components/internals/VtuberCanvas.vue')['default']
    VtuberConfig: typeof import('./components/vtuber/VtuberConfig.vue')['default']
    WebCamera: typeof import('./components/internals/WebCamera.vue')['default']
  }
}

export {}
